# Site settings
title:          "നാര.ങ്ങ"
description:    "A good collection of short stories"
baseurl:        "/"
url:            "https://naran.ga"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Vinu K
  url:          https://gnulinuxmate.com/
  email:        vinu@gnulinuxmate.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
